@@grammar::BAAS
@@ignorecase::True

start        = statement $ ;

statement    = terminate | hold_keys | press_keys | release_keys ;
	
terminate    = 'terminate' ;
	
hold_keys    = 'hold' right:keys ;
release_keys = 'release' right:keys ;
	
press_keys   = 'press' left:[ multiplier ] right:keys ;
multiplier   = right:num ( 'time' | 'times' ) ;
	
keys         = [ 'keys' | 'key' ] right:{ key }+ ;
key          = 'shift' | 'control' | 'alt' | alpha_num ;

alpha_num    = alpha | num ;
alpha        = /[a-z]+/ ;
num          = /[0-9]+/ ;
