@@grammar::BAAS
@@ignorecase::True

start = statements $ ;

statements
	=
	{ statement }+
	;

statement
	=
	terminate | hold_keys | press_keys | release_keys
	;
	
terminate
	=
	'terminate'
	;
	
hold_keys
	=
	'hold' keys
	;
	
press_keys
	=
	'press' keys [ multiplier ]
	;
	
multiplier
	=
	'repeat' num
	;
	
release_keys
	=
	'release' keys
	;

keys
	=
	{ key }+
	;
	
key
	=
	'shift' | 'control' | 'alt' | alpha_num
	;
	
alpha_num
	=
	alpha | num
	;

alpha
	=
	a | b | c | d | e | f | g | h | i | j | k | l | m | n | o | p | q | r | s | t | u | v | w | x | y | z
	;
a
	=
	'a' | 'alpha'
	;
b
	=
	'b' | 'bravo'
	;
c
	=
	'c' | 'charlie'
	;
d
	=
	'd' | 'delta'
	;
e
	=
	'e' | 'echo'
	;
f
	=
	'f' | 'foxtrot'
	;
g
	=
	'g' | 'golf'
	;
h
	=
	'h' | 'hotel'
	;
i
	=
	'i' | 'india'
	;
j
	=
	'j' | 'juliet'
	;
k
	=
	'k' | 'kilo'
	;
l
	=
	'l' | 'lima'
	;
m
	=
	'm' | 'mike'
	;
n
	=
	'n' | 'november'
	;
o
	=
	'o' | 'oscar'
	;
p
	=
	'p' | 'papa'
	;
q
	=
	'q' | 'quebec'
	;
r
	=
	'r' | 'romeo'
	;
s
	=
	's' | 'sierra'
	;
t
	=
	't' | 'tango'
	;
u
	=
	'uniform'
	;
v
	=
	'victor'
	;
w
	=
	'whiskey'
	;
x
	=
	'xray'
	;
y
	=
	'yankee'
	;
z
	=
	'zulu'
	;
	
num
	=
	num2 num1 | num2 | num1
	;
	
num1
	=
	zero | one | two | three | four | five | six | seven | eight | nine
	;
num2
	=
	ten | eleven | twelve | thirteen | fourteen | fifteen | sixteen | seventeen | eighteen | nineteen | twenty
	;
	
ten
	=
	'10' | 'ten' | 'tin' | one zero
	;
eleven
	=
	'11' | 'eleven' | one one
	;
twelve
	=
	'12' | 'twelve' | one two
	;
thirteen
	=
	'13' | 'thirteen' | one three
	;
fourteen
	=
	'14' | 'fourteen' | one four
	;
fifteen
	=
	'15' | 'fifteen' | one five
	;
sixteen
	=
	'16' | 'sixteen' | one six
	;
seventeen
	=
	'17' | 'seventeen' | one seven
	;
eighteen
	=
	'18' | 'eighteen' | one eight
	;
nineteen
	=
	'19' | 'nineteen' | one nine
	;
twenty
	=
	'20' | 'twenty' | two zero
	;

zero
	=
	'0' | 'zero'
	;
one
	=
	'1' | 'one' | 'wun' | 'won'
	;
two
	=
	'2' | 'two' | 'too' | 'to'
	;
three
	=
	'3' | 'three' | 'tree'
	;
four
	=
	'4' | 'four' | 'fower' | 'for'
	;
five
	=
	'5' | 'five' | 'fife'
	;
six
	=
	'6' | 'six'
	;
seven
	=
	'7' | 'seven'
	;
eight
	=
	'8' | 'eight' | 'ait'
	;
nine
	=
	'9' | 'nine' | 'niner'
	;
